export interface LoteriaCard {
  id: number;
  name: string;
  emoji: string;
  color: string;
}

export const LOTERIA_CARDS: LoteriaCard[] = [
  { id: 1, name: "El gallo", emoji: "🐓", color: "#fff9db" },
  { id: 2, name: "El diablito", emoji: "😈", color: "#ffe3e3" },
  { id: 3, name: "La dama", emoji: "💃", color: "#fff0f6" },
  { id: 4, name: "El catrín", emoji: "🤵", color: "#e8f7ff" },
  { id: 5, name: "El paraguas", emoji: "☂️", color: "#f3f0ff" },
  { id: 6, name: "La sirena", emoji: "🧜‍♀️", color: "#e3fafc" },
  { id: 7, name: "La escalera", emoji: "🪜", color: "#fff9db" },
  { id: 8, name: "La botella", emoji: "🍾", color: "#ebfbee" },
  { id: 9, name: "El barril", emoji: "🛢️", color: "#fff4e6" },
  { id: 10, name: "El árbol", emoji: "🌳", color: "#ebfbee" },
  { id: 11, name: "El melón", emoji: "🍈", color: "#f4fce8" },
  { id: 12, name: "El valiente", emoji: "🧍🏻‍♂️", color: "#fff5f5" },
  { id: 13, name: "El gorrito", emoji: "👒", color: "#fff0f6" },
  { id: 14, name: "La muerte", emoji: "💀", color: "#f8f9fa" },
  { id: 15, name: "La pera", emoji: "🍐", color: "#f4fce8" },
  { id: 16, name: "La bandera", emoji: "🇲🇽", color: "#fff5f5" },
  { id: 17, name: "El bandolón", emoji: "🪕", color: "#fff4e6" },
  { id: 18, name: "El violoncello", emoji: "🎻", color: "#fff4e6" },
  { id: 19, name: "La garza", emoji: "🦩", color: "#fff0f6" },
  { id: 20, name: "El pájaro", emoji: "🐦", color: "#e8f7ff" },
  { id: 21, name: "La mano", emoji: "✋", color: "#fff9db" },
  { id: 22, name: "La bota", emoji: "👢", color: "#fff4e6" },
  { id: 23, name: "La luna", emoji: "🌙", color: "#f3f0ff" },
  { id: 24, name: "El cotorro", emoji: "🦜", color: "#ebfbee" },
  { id: 25, name: "El borracho", emoji: "🥴", color: "#fff9db" },
  { id: 26, name: "El negrito", emoji: "🧑🏿", color: "#e8f7ff" },
  { id: 27, name: "El corazón", emoji: "❤️", color: "#ffe3e3" },
  { id: 28, name: "La sandía", emoji: "🍉", color: "#ffe3e3" },
  { id: 29, name: "El tambor", emoji: "🥁", color: "#fff4e6" },
  { id: 30, name: "El camarón", emoji: "🦐", color: "#ffe3e3" },
  { id: 31, name: "Las jaras", emoji: "🏹", color: "#fff9db" },
  { id: 32, name: "El músico", emoji: "👨🏻‍🎤", color: "#f3f0ff" },
  { id: 33, name: "La araña", emoji: "🕷️", color: "#f8f9fa" },
  { id: 34, name: "El soldado", emoji: "💂", color: "#e8f7ff" },
  { id: 35, name: "La estrella", emoji: "⭐", color: "#fff9db" },
  { id: 36, name: "El cazo", emoji: "🍲", color: "#fff4e6" },
  { id: 37, name: "El mundo", emoji: "🌎", color: "#e8f7ff" },
  { id: 38, name: "El apache", emoji: "👳🏽‍♂️", color: "#fff4e6" },
  { id: 39, name: "El nopal", emoji: "🌵", color: "#ebfbee" },
  { id: 40, name: "El alacrán", emoji: "🦂", color: "#fff9db" },
  { id: 41, name: "La rosa", emoji: "🌹", color: "#fff0f6" },
  { id: 42, name: "La calavera", emoji: "☠️", color: "#f8f9fa" },
  { id: 43, name: "La campana", emoji: "🔔", color: "#fff9db" },
  { id: 44, name: "El cantarito", emoji: "🏺", color: "#fff4e6" },
  { id: 45, name: "El venado", emoji: "🦌", color: "#fff4e6" },
  { id: 46, name: "El sol", emoji: "☀️", color: "#fff9db" },
  { id: 47, name: "La corona", emoji: "👑", color: "#fff9db" },
  { id: 48, name: "La chalupa", emoji: "🛶", color: "#e8f7ff" },
  { id: 49, name: "El pino", emoji: "🌲", color: "#ebfbee" },
  { id: 50, name: "El pescado", emoji: "🐟", color: "#e3fafc" },
  { id: 51, name: "La palma", emoji: "🌴", color: "#ebfbee" },
  { id: 52, name: "La maceta", emoji: "🪴", color: "#fff4e6" },
  { id: 53, name: "El arpa", emoji: "🪉", color: "#f3f0ff" },
  { id: 54, name: "La rana", emoji: "🐸", color: "#ebfbee" }
];
